Add gargish leather and studded armor
modernuo/ModernUO pull request #559
Opened 2021-03-24 13:36 UTC by immaciek

author: @ijurek

2021-03-24 13:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/modernuo/ModernUO?pullRequest=559) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/modernuo/ModernUO?pullRequest=559) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/modernuo/ModernUO?pullRequest=559) it.</sub>

2021-03-24 16:52 UTC, kamronbatman commented
With the way the CLA is set up, I need @ijurek to sign the CLA. Or you (or me or someone else) needs to redo the commits and resubmit the PR.
Sorry this is so complicated.

I can take this PR and recode it and make a new one.

2021-03-24 17:09 UTC, immaciek commented
> With the way the CLA is set up, I need @ijurek to sign the CLA. Or you (or me or someone else that has already signed the CLA) needs to redo the commits and resubmit the PR.
> Sorry this is so complicated.
> 
> I can take this PR and recode it and make a new one.

Hey - he did sign the CLA, it wouldn't pass the checks otherwise.

2021-03-24 20:29 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Leather/FemaleGargishLeatherArms.cs
> +
extra line

2021-03-24 20:31 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Leather/GargishLeatherArms.cs
> +    class GargishLeatherArms : BaseArmor
Add `public` modifier

2021-03-24 20:32 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Leather/GargishLeatherArms.cs
> +
Remove extra line on all files that have it. (I also wish we had a good linter to do this automatically)

2021-03-26 23:32 UTC, kamronbatman commented
This looks great! Can you add back the TypeAliases?

2021-03-31 20:47 UTC, kamronbatman requested changes

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Leather/GargishLeatherArmsType1.cs
> +    public class GargishLeatherArmsType1 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.GargishLeatherArms")]
    public class GargishLeatherArmsType1 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Leather/GargishLeatherArmsType2.cs
> +    public class GargishLeatherArmsType2 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.FemaleGargishLeatherArms")]
    public class GargishLeatherArmsType2 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Leather/GargishLeatherChestType1.cs
> +    public class GargishLeatherChestType1 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.GargishLeatherChest")]
    public class GargishLeatherChestType1 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Leather/GargishLeatherChestType2.cs
> +    public class GargishLeatherChestType2 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.FemaleGargishLeatherChest")]
    public class GargishLeatherChestType2 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Leather/GargishLeatherKiltType1.cs
> +    public class GargishLeatherKiltType1 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.GargishLeatherKilt")]
    public class GargishLeatherKiltType1 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Leather/GargishLeatherKiltType2.cs
> +    public class GargishLeatherKiltType2 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.FemaleGargishLeatherKilt")]
    public class GargishLeatherKiltType2 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Leather/GargishLeatherLegsType1.cs
> +    public class GargishLeatherLegsType1 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.GargishLeatherLegs")]
    public class GargishLeatherLegsType1 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Leather/GargishLeatherLegsType2.cs
> +    public class GargishLeatherLegsType2 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.FemaleGargishLeatherLegs")]
    public class GargishLeatherLegsType2 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Studded/GargishStuddedArmsType1.cs
> +    public class GargishStuddedArmsType1 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.GargishStuddedArms")]
    public class GargishStuddedArmsType1 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Studded/GargishStuddedArmsType2.cs
> +    public class GargishStuddedArmsType2 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.FemaleGargishStuddedArms")]
    public class GargishStuddedArmsType2 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Studded/GargishStuddedChestType1.cs
> +    public class GargishStuddedChestType1 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.GargishStuddedChest")]
    public class GargishStuddedChestType1 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Studded/GargishStuddedChestType2.cs
> +    public class GargishStuddedChestType2 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.FemaleGargishStuddedChest")]
    public class GargishStuddedChestType2 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Studded/GargishStuddedKiltType1.cs
> +    public class GargishStuddedKiltType1 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.GargishStuddedKilt")]
    public class GargishStuddedKiltType1 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Studded/GargishStuddedKiltType2.cs
> +    public class GargishStuddedKiltType2 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.FemaleGargishStuddedKilt")]
    public class GargishStuddedKiltType2 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Studded/GargishStuddedLegsType1.cs
> +    public class GargishStuddedLegsType1 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.GargishStuddedLegs")]
    public class GargishStuddedLegsType1 : BaseArmor
```

2021-03-31 20:47 UTC, kamronbatman commented on Projects/UOContent/Items/Armor/Studded/GargishStuddedLegsType2.cs
> +    public class GargishStuddedLegsType2 : BaseArmor
```suggestion
    [TypeAlias("Server.Items.FemaleGargishStuddedLegs")]
    public class GargishStuddedLegsType2 : BaseArmor
```

2021-04-01 00:28 UTC, kamronbatman approved these changes

2021-04-01 00:29 UTC, merged